titleurl: TheWebsitesGuy.co.uk
title: The Websites Guy
email: info@thewebsitesguy.co.uk
description: TheWebsitesGuy.co.uk performance, speed and optimisation
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thewebsitesguy.co.uk"
twitter_username: thewebsitesguy
github_username:  proochster
theme-colour: '#ff5050'

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  
highlighter: rouge

sass:
  sass_dir: ./_styles
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .firebaserc
  - database.rules.json
  - firebase.json
  - package.json
  - functions
