title: TheWebsitesGuy.co.uk
email: info@thewebsitesguy.co.uk
description: www.thewebsitesguy.co.uk webpage and blog
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thewebsitesguy.co.uk"
twitter_username: thewebsitesguy
github_username:  proochster
theme-colour: '#054D76'

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  
highlighter: rouge

sass:
  sass_dir: ./_styles
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
